services:

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - XDEBUG_VERSION=${XDEBUG_VERSION}
    volumes:
      - ./project:/app
      - composer:/root/.composer/cache
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - db

  proxy:
    image: jwilder/nginx-proxy:1.5-alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "${NGINX_PORT}:80"

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./project:/app
    environment:
      VIRTUAL_HOST: ${NGINX_VIRTUAL_HOST}
    depends_on:
      - php-fpm
      - proxy

  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-database}
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - ./data/postgres-${POSTGRES_VERSION:-16}:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-database}"]
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:8
    restart: unless-stopped
    ports:
      - ${PGADMIN_PORT:-8888}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: username@example.com
      PGADMIN_DEFAULT_PASSWORD: password
      VIRTUAL_HOST: ${PGADMIN_VIRTUAL_HOST:-pgadmin.test}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  composer:
  pgadmin-data:
